import { useState } from "react";

export default function BankOperationForm({ onSave, onCancel }) {
  const [type, setType] = useState('Bank Withdraw');
  const [currency, setCurrency] = useState('SAR');
  const [amount, setAmount] = useState('');
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [description, setDescription] = useState('');
  const [note, setNote] = useState('');
  const submit = (event) => { event.preventDefault(); if (!amount || Number(amount) <= 0) return alert('সঠিক পরিমাণ লিখুন!'); onSave({ type, currency, amount, date, description, note }); };
  return <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-200 space-y-4"><div className="flex items-center justify-between border-b border-gray-100 pb-3"><button onClick={onCancel} className="text-gray-500"><i className="fa-solid fa-arrow-left text-lg"></i></button><h3 className="font-bold text-blue-600">Bank Operation</h3><div className="w-5"></div></div><form onSubmit={submit} className="space-y-3"><select value={type} onChange={(e) => setType(e.target.value)} className="w-full border border-gray-300 rounded-xl px-3 py-2 text-sm"><option value="Bank Withdraw">Withdraw from Bank to Cash</option><option value="Bank Deposit">Deposit Cash to Bank</option></select><div className="grid grid-cols-2 gap-2"><select value={currency} onChange={(e) => setCurrency(e.target.value)} className="border border-gray-300 rounded-xl px-3 py-2 text-sm"><option>SAR</option><option>BDT</option></select><input type="number" step="any" min="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Amount" className="border border-gray-300 rounded-xl px-3 py-2 text-sm" required /></div><input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="w-full border border-gray-300 rounded-xl px-3 py-2 text-sm" required /><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description" className="w-full border border-gray-300 rounded-xl px-3 py-2 text-sm" /><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Note" rows="2" className="w-full border border-gray-300 rounded-xl p-3 text-sm resize-none"></textarea><button className="w-full bg-blue-600 text-white font-bold py-3 rounded-xl"><i className="fa-solid fa-building-columns"></i> Save Operation</button></form></div>;
}
